services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Helhum\TopImage\:
        resource: '../Classes/*'

    Helhum\TopImage\TCA\CropVariantGenerator:
        factory: ['@Helhum\TopImage\TCA\CropVariantGeneratorFactory', 'createGenerator']

    Helhum\TopImage\Listener\CropVariantTcaListener:
        tags:
          - name: event.listener
            identifier: 'top-image-tca'
            method: addCropVariantsToTca
